# name: CI Workflow

# on:
#   push:
#     branches:
#       - main
#       - github-actions
#   # pull_request:
#   # create:
#   #   tags: "*"

# jobs:
#   code_quality:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Lint Code
#         run: npm run lint
  
#   build_app:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Install Dependencies
#         run: npm install
#       - name: Build App
#         run: npm run build

#   publish_npm:
#     if: startsWith(github.ref, 'refs/tags/')
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Publish to NPM
#         run: |
#           echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
#           npm publish


on:
  push:
    branches:
      - main
      - github-actions
    tags:
      - 'v*'  # Triggers when a version tag is pushed (e.g., v1.0.0)

jobs:
  lint_scss:  # Code quality check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: src-pages

      - name: Install dependencies
        run: npm install

      - name: Lint SCSS files
        run: npx stylelint "**/*.scss"  # Lints SCSS files for code quality

  build_css:  # SCSS to CSS compilation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: src-pages
            fetch-depth: 10
            submodules: true

      - name: Make destination directory for compiled CSS
        run: mkdir -vp /tmp/repo-name/assets/css

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.6.0
        with:
          source: _scss/main.scss
          destination: /tmp/repo-name/assets/css/main.css

      - name: Checkout destination Git branch
        uses: actions/checkout@v2
        with:
            ref: pr-pages
            fetch-depth: 1

      - name: Move compiled CSS to path within pr-pages branch
        run: mv /tmp/repo-name/assets/css assets/

      - name: Add and Commit changes to pr-pages branch
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add assets/css/*
          git commit -m 'Updates compiled CSS files'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: pr-pages

      - name: Initialize Pull Request
        uses: gha-utilities/init-pull-request@v0.0.4
        with:
          pull_request_token: ${{ secrets.GITHUB_TOKEN }}
          head: pr-pages
          base: gh-pages
          title: 'Updates site files from latest Actions build'
          body: >
            This pull request updates the site with the latest CSS changes.

  publish_npm:  # Publish to NPM on tag creation
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')  # Triggers only for version tags
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Publish to NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}  # Use npm token stored in secrets
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          npm publish

